name: batect lint:docker
on: [pull_request]
jobs:
  hadolint:
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256color
      BATECT_CACHE_TYPE: directory
      BATECT_ENABLE_TELEMETRY: true
      
    steps:
      - uses: actions/checkout@v3.0.2

      - name: Validate Batect wrapper scripts
        uses: batect/batect-wrapper-validation-action@v0.4.0

      - name: Cache Batect
        uses: actions/cache@v3.0.9
        with:
          path: .batect/caches
          key: batect-${{ hashFiles('batect') }}

      - name: batect lint:docker
        run: ./batect lint:docker
